### ISSUE TITLE
Kernel not found

### ISSUE THREAD

**Issue by knxwille** [Xtr126/androidx86-installer-qemu-linux#3]
Some android builds, delivering with multiple kernel. ( kernel-5.10 and kenel-5.15 etc.) 
Launcher looking for "kernel" and cannot find the kernel, writing an error and exit.
Yo should check kernel file thats named other than "kernel"

**Comment by Xtr126** [comment]
Thanks for reporting, the script will look for kernel* from now. 
For ISO images that have kernels with a irregular name that is not in the form of kernel* (kernel-5.10), we will figure out a solution later.
In all of the Android-x86 systems I used, the file is named "kernel" so I just check that. After they introduced system.efs instead of system.sfs, the script had to be updated for that too.
